import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/app/lib/supabase";

export const dynamic = "force-dynamic";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SeedLead {
  companyName: string;
  website?: string;
  contactName: string;
  title: string;
  email: string;
  phone?: string;
  triggerEvent: string;
  intelligenceSummary: string;
  status: string;
  notes?: string;
  tags?: string[];
  aiScore?: number;
  dealValue?: number;
  source?: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Seed data per industry
// ---------------------------------------------------------------------------

const NOW = new Date().toISOString();

const SEED_DATA: Record<string, SeedLead[]> = {
  saas: [
    {
      companyName: "Notion",
      website: "notion.so",
      contactName: "Akshay Kothari",
      title: "Chief Operating Officer",
      email: "akshay.kothari@notion.so",
      phone: "+1 (415) 555-0101",
      triggerEvent: "Expanded headcount 40% YoY — now 500+ employees",
      intelligenceSummary: "Notion is scaling its enterprise sales motion aggressively after crossing $100M ARR. COO Akshay Kothari has been vocal about investing in partner integrations. Strong signal for a workflow automation pitch.",
      status: "new",
      tags: ["Series C", "PLG", "Enterprise Expansion"],
      aiScore: 92,
      dealValue: 85000,
      source: "LinkedIn Signal",
      updatedAt: NOW,
    },
    {
      companyName: "Figma",
      website: "figma.com",
      contactName: "Sho Kuwamoto",
      title: "VP of Product",
      email: "sho.kuwamoto@figma.com",
      phone: "+1 (415) 555-0102",
      triggerEvent: "Recently raised $200M Series E at $10B valuation",
      intelligenceSummary: "Figma is doubling down on enterprise features post-Series E. VP of Product Sho Kuwamoto is leading the collaboration platform expansion. Decision maker for tooling integrations.",
      status: "contacted",
      tags: ["Series E", "Design", "Enterprise"],
      aiScore: 88,
      dealValue: 120000,
      source: "Crunchbase",
      updatedAt: NOW,
    },
    {
      companyName: "Linear",
      website: "linear.app",
      contactName: "Karri Saarinen",
      title: "CEO & Co-founder",
      email: "karri@linear.app",
      triggerEvent: "Job postings for 15+ engineers — scaling product team",
      intelligenceSummary: "Linear is hiring aggressively to meet demand from mid-market engineering teams. CEO Karri Saarinen personally reviews vendor partnerships. Strong alignment if you serve developer tooling.",
      status: "new",
      tags: ["Seed-funded", "Dev Tools", "Hiring Signal"],
      aiScore: 85,
      dealValue: 40000,
      source: "Job Board Monitor",
      updatedAt: NOW,
    },
    {
      companyName: "Vercel",
      website: "vercel.com",
      contactName: "Malte Ubl",
      title: "CTO",
      email: "malte.ubl@vercel.com",
      phone: "+1 (650) 555-0103",
      triggerEvent: "Launched new Enterprise tier with advanced analytics",
      intelligenceSummary: "Vercel is moving upmarket with its Enterprise offering, targeting Fortune 1000 engineering teams. CTO Malte Ubl is architecting partnerships with DevOps vendors. Excellent fit for infrastructure tooling.",
      status: "qualified",
      tags: ["Series C", "Frontend", "Enterprise Tier"],
      aiScore: 90,
      dealValue: 95000,
      source: "Product Hunt",
      updatedAt: NOW,
    },
    {
      companyName: "Stripe",
      website: "stripe.com",
      contactName: "Claire Hughes Johnson",
      title: "COO",
      email: "claire.hughes@stripe.com",
      phone: "+1 (650) 555-0104",
      triggerEvent: "Expanded to 46 countries — new international payment rails",
      intelligenceSummary: "Stripe continues its global expansion play, recently adding Southeast Asia markets. COO Claire Hughes Johnson oversees vendor relationships for operations tooling. High-value account with long sales cycles.",
      status: "new",
      tags: ["Fintech", "Global Expansion", "High ACV"],
      aiScore: 78,
      dealValue: 200000,
      source: "Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "Intercom",
      website: "intercom.com",
      contactName: "Des Traynor",
      title: "Chief Strategy Officer",
      email: "des.traynor@intercom.com",
      triggerEvent: "Launched AI-first product suite — repositioning brand",
      intelligenceSummary: "Intercom is mid-transformation, pivoting its entire product around AI. CSO Des Traynor is leading the strategic vendor review for the new stack. Immediate opportunity for AI tooling and data infrastructure plays.",
      status: "contacted",
      tags: ["AI Pivot", "Customer Success", "Rebranding"],
      aiScore: 82,
      dealValue: 75000,
      source: "TechCrunch",
      updatedAt: NOW,
    },
    {
      companyName: "Loom",
      website: "loom.com",
      contactName: "Shahed Khan",
      title: "Co-founder & Head of Growth",
      email: "shahed@loom.com",
      phone: "+1 (415) 555-0105",
      triggerEvent: "Acquired by Atlassian — integration roadmap underway",
      intelligenceSummary: "Loom's acquisition by Atlassian has triggered a significant integration roadmap review. Shahed Khan is coordinating vendor relationships for the new combined platform. Strong signal for collaboration tooling.",
      status: "qualified",
      tags: ["Acquired", "Atlassian Ecosystem", "Video"],
      aiScore: 75,
      dealValue: 60000,
      source: "M&A Alert",
      updatedAt: NOW,
    },
    {
      companyName: "Calendly",
      website: "calendly.com",
      contactName: "Annie Pearl",
      title: "Chief Product Officer",
      email: "annie.pearl@calendly.com",
      triggerEvent: "Grew to 20M users — building enterprise features",
      intelligenceSummary: "Calendly is transitioning from SMB to enterprise with a new CPO leading the charge. Annie Pearl joined from Glassdoor and is actively reviewing the vendor ecosystem. Strong fit for enterprise SaaS tooling.",
      status: "new",
      tags: ["Enterprise Pivot", "SaaS", "Scheduling"],
      aiScore: 72,
      dealValue: 55000,
      source: "LinkedIn",
      updatedAt: NOW,
    },
    {
      companyName: "Retool",
      website: "retool.com",
      contactName: "David Hsu",
      title: "CEO",
      email: "david@retool.com",
      phone: "+1 (415) 555-0106",
      triggerEvent: "Recently raised Series C — $3.2B valuation",
      intelligenceSummary: "Retool's Series C positions it to dominate internal tooling for enterprises. CEO David Hsu is focused on partnerships that expand the developer ecosystem. High intent signal for infrastructure and API vendors.",
      status: "proposal",
      tags: ["Series C", "Low-Code", "Developer Tools"],
      aiScore: 88,
      dealValue: 110000,
      source: "Crunchbase",
      updatedAt: NOW,
    },
    {
      companyName: "Airtable",
      website: "airtable.com",
      contactName: "Howie Liu",
      title: "CEO & Co-founder",
      email: "howie@airtable.com",
      triggerEvent: "Launched Airtable AI — expanding platform integrations",
      intelligenceSummary: "Airtable's AI launch is driving renewed interest from enterprise accounts. CEO Howie Liu is personally championing partnerships with data and automation vendors. Perfect timing for a platform integration discussion.",
      status: "new",
      tags: ["AI Launch", "No-Code", "Enterprise"],
      aiScore: 80,
      dealValue: 80000,
      source: "Product Hunt",
      updatedAt: NOW,
    },
    {
      companyName: "Webflow",
      website: "webflow.com",
      contactName: "Linda Tong",
      title: "CEO",
      email: "linda.tong@webflow.com",
      triggerEvent: "Crossed 300K customers — hiring VP Sales",
      intelligenceSummary: "Webflow is building out its enterprise sales muscle after rapid bottom-up growth. New CEO Linda Tong is restructuring go-to-market and actively sourcing vendor partnerships for the sales stack.",
      status: "new",
      tags: ["Growth Stage", "No-Code", "Enterprise Sales"],
      aiScore: 68,
      dealValue: 45000,
      source: "Job Board Monitor",
      updatedAt: NOW,
    },
    {
      companyName: "Zapier",
      website: "zapier.com",
      contactName: "Mike Knoop",
      title: "Co-founder & Head of AI",
      email: "mike@zapier.com",
      phone: "+1 (888) 555-0107",
      triggerEvent: "Launched Zapier Interfaces — no-code app builder entering new market",
      intelligenceSummary: "Zapier is expanding beyond automation into full app building, putting it in direct competition with Retool and Glide. Mike Knoop leads AI strategy and is evaluating infrastructure partnerships for the new product.",
      status: "contacted",
      tags: ["AI Expansion", "Automation", "Platform Play"],
      aiScore: 76,
      dealValue: 65000,
      source: "Blog Monitor",
      updatedAt: NOW,
    },
  ],

  agency: [
    {
      companyName: "IDEO",
      website: "ideo.com",
      contactName: "Sandy Speicher",
      title: "CEO",
      email: "sandy.speicher@ideo.com",
      phone: "+1 (650) 555-0201",
      triggerEvent: "Launched new AI design practice — hiring 30 specialists",
      intelligenceSummary: "IDEO is building a dedicated AI design practice in response to client demand. CEO Sandy Speicher is leading the strategic pivot and actively reviewing vendor tools for design and research workflows.",
      status: "new",
      tags: ["Innovation", "AI Practice", "Design Consulting"],
      aiScore: 82,
      dealValue: 90000,
      source: "PR Newswire",
      updatedAt: NOW,
    },
    {
      companyName: "Wunderman Thompson",
      website: "wundermanthompson.com",
      contactName: "Mel Edwards",
      title: "Global CEO",
      email: "mel.edwards@wundermanthompson.com",
      phone: "+1 (212) 555-0202",
      triggerEvent: "Won $300M Fortune 500 global retainer",
      intelligenceSummary: "Wunderman Thompson secured a major global marketing retainer, triggering a significant vendor review for campaign analytics and CRM tooling. Global CEO Mel Edwards is overseeing the platform modernization.",
      status: "contacted",
      tags: ["Enterprise Retainer", "Global Agency", "Marketing Tech"],
      aiScore: 78,
      dealValue: 150000,
      source: "AdAge",
      updatedAt: NOW,
    },
    {
      companyName: "R/GA",
      website: "rga.com",
      contactName: "Sean Lyons",
      title: "CEO",
      email: "sean.lyons@rga.com",
      triggerEvent: "Expanding to APAC — opening Singapore and Tokyo offices",
      intelligenceSummary: "R/GA is making a significant APAC push with new offices in Singapore and Tokyo. CEO Sean Lyons is coordinating the regional vendor onboarding. Strong signal for localization, analytics, and project management tooling.",
      status: "new",
      tags: ["APAC Expansion", "Digital Agency", "New Markets"],
      aiScore: 72,
      dealValue: 85000,
      source: "Campaign Asia",
      updatedAt: NOW,
    },
    {
      companyName: "Huge",
      website: "hugeinc.com",
      contactName: "Mat Baxter",
      title: "Global CEO",
      email: "mat.baxter@hugeinc.com",
      phone: "+1 (718) 555-0203",
      triggerEvent: "Rebranded as experience design consultancy — new practice areas",
      intelligenceSummary: "Huge rebranded under new CEO Mat Baxter, pivoting toward experience design and away from pure digital production. Actively evaluating new vendor ecosystem to support the repositioned service offering.",
      status: "new",
      tags: ["Rebrand", "UX Design", "Consultancy"],
      aiScore: 65,
      dealValue: 70000,
      source: "Digiday",
      updatedAt: NOW,
    },
    {
      companyName: "Deloitte Digital",
      website: "deloittedigital.com",
      contactName: "Jerome Buvat",
      title: "Managing Director, Digital Strategy",
      email: "jerome.buvat@deloitte.com",
      phone: "+1 (212) 555-0204",
      triggerEvent: "Launched CX transformation practice — 200 new hires",
      intelligenceSummary: "Deloitte Digital is scaling its CX practice with a 200-person hiring push. MD Jerome Buvat is responsible for building out the vendor ecosystem that supports the new practice area. High ACV potential.",
      status: "qualified",
      tags: ["Big 4", "CX Practice", "Digital Transformation"],
      aiScore: 85,
      dealValue: 200000,
      source: "LinkedIn",
      updatedAt: NOW,
    },
    {
      companyName: "Accenture Song",
      website: "accenture.com",
      contactName: "David Droga",
      title: "CEO, Accenture Song",
      email: "david.droga@accenture.com",
      triggerEvent: "Acquired Droga5 — integrating creative and consulting capabilities",
      intelligenceSummary: "Accenture Song continues integrating its creative acquisitions under David Droga. The integration is triggering a major vendor consolidation review for creative tools, analytics, and collaboration platforms.",
      status: "contacted",
      tags: ["Acquisition Integration", "Creative Consultancy", "Accenture"],
      aiScore: 80,
      dealValue: 175000,
      source: "Ad Week",
      updatedAt: NOW,
    },
    {
      companyName: "VaynerMedia",
      website: "vaynermedia.com",
      contactName: "Claude Silver",
      title: "Chief Heart Officer & Chief of Staff",
      email: "claude.silver@vaynermedia.com",
      phone: "+1 (212) 555-0205",
      triggerEvent: "Scaling social commerce team — 40 new roles",
      intelligenceSummary: "VaynerMedia is building a dedicated social commerce practice with aggressive hiring. Claude Silver coordinates strategic partnerships for operational tooling. Strong opportunity for social listening and campaign analytics vendors.",
      status: "new",
      tags: ["Social Commerce", "Content Agency", "Hiring Signal"],
      aiScore: 68,
      dealValue: 60000,
      source: "LinkedIn Jobs",
      updatedAt: NOW,
    },
    {
      companyName: "Publicis Sapient",
      website: "publicissapient.com",
      contactName: "Nigel Vaz",
      title: "Global CEO",
      email: "nigel.vaz@publicissapient.com",
      triggerEvent: "Expanding data and AI practice — seeking vendor partnerships",
      intelligenceSummary: "Publicis Sapient is positioning data and AI as its growth engine for the next 3 years. CEO Nigel Vaz is building the vendor ecosystem to support client engagements. Excellent fit for data platform vendors.",
      status: "new",
      tags: ["Data & AI", "Digital Consulting", "Partnership Seeking"],
      aiScore: 83,
      dealValue: 140000,
      source: "Publicis Earnings Call",
      updatedAt: NOW,
    },
    {
      companyName: "McKinsey Digital",
      website: "mckinsey.com",
      contactName: "Rodney Zemmel",
      title: "Global Leader, McKinsey Digital",
      email: "rodney.zemmel@mckinsey.com",
      phone: "+1 (212) 555-0206",
      triggerEvent: "Launched QuantumBlack AI division — 1,000 data scientists hired",
      intelligenceSummary: "McKinsey Digital is scaling its AI practice through QuantumBlack. Rodney Zemmel oversees the technology ecosystem for digital client engagements. Strategic partner opportunities exist across AI tooling and data infrastructure.",
      status: "qualified",
      tags: ["AI Division", "Top Tier Consulting", "QuantumBlack"],
      aiScore: 88,
      dealValue: 300000,
      source: "McKinsey.com",
      updatedAt: NOW,
    },
    {
      companyName: "BCG X",
      website: "bcgx.com",
      contactName: "Sylvain Duranton",
      title: "Global Leader, BCG X",
      email: "sylvain.duranton@bcgx.com",
      triggerEvent: "BCG X scaling to 3,000 technologists globally",
      intelligenceSummary: "BCG X is BCG's tech build and design unit, rapidly scaling to challenge traditional SIs. Sylvain Duranton is building the vendor stack to support client co-builds. High potential for platform and developer tooling partnerships.",
      status: "new",
      tags: ["Tech Build", "BCG", "Global Scaling"],
      aiScore: 86,
      dealValue: 250000,
      source: "BCG Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "Bain & Company",
      website: "bain.com",
      contactName: "Manny Maceda",
      title: "Worldwide Managing Partner",
      email: "manny.maceda@bain.com",
      triggerEvent: "Launched Results Delivery practice — new tooling requirements",
      intelligenceSummary: "Bain's Results Delivery practice is scaling with new technology requirements for tracking client outcomes. Worldwide Managing Partner Manny Maceda is sponsoring the vendor selection for outcomes-tracking tooling.",
      status: "contacted",
      tags: ["Consulting", "Results Delivery", "Enterprise Tooling"],
      aiScore: 77,
      dealValue: 180000,
      source: "Consulting Magazine",
      updatedAt: NOW,
    },
    {
      companyName: "PwC Digital",
      website: "pwc.com",
      contactName: "Joe Atkinson",
      title: "Chief Products & Technology Officer",
      email: "joe.atkinson@pwc.com",
      phone: "+1 (646) 555-0207",
      triggerEvent: "$1B investment in digital transformation capabilities over 3 years",
      intelligenceSummary: "PwC Digital announced a $1B investment in its digital and AI capabilities. CPO Joe Atkinson is overseeing the technology vendor selection for this multiyear transformation. Strategic partner opportunity with long-term revenue potential.",
      status: "qualified",
      tags: ["Big 4", "Digital Investment", "Multi-Year Deal"],
      aiScore: 90,
      dealValue: 350000,
      source: "PwC Press Release",
      updatedAt: NOW,
    },
  ],

  realestate: [
    {
      companyName: "CBRE",
      website: "cbre.com",
      contactName: "Emma Giamartino",
      title: "Chief Financial & Investment Officer",
      email: "emma.giamartino@cbre.com",
      phone: "+1 (310) 555-0301",
      triggerEvent: "Listed $50M commercial portfolio in Southeast markets",
      intelligenceSummary: "CBRE's Southeast division is managing a major portfolio listing with complex multi-asset coordination. CFO Emma Giamartino is overseeing investment technology decisions. Opportunity for deal management and analytics platforms.",
      status: "new",
      tags: ["Commercial RE", "Portfolio Sale", "Fortune 500"],
      aiScore: 82,
      dealValue: 120000,
      source: "CoStar",
      updatedAt: NOW,
    },
    {
      companyName: "JLL",
      website: "jll.com",
      contactName: "Christian Ulbrich",
      title: "CEO",
      email: "christian.ulbrich@jll.com",
      phone: "+1 (312) 555-0302",
      triggerEvent: "Expanding to 3 new markets — Dallas, Miami, Phoenix",
      intelligenceSummary: "JLL is entering three high-growth Sun Belt markets simultaneously, driving demand for brokerage tooling and market intelligence platforms. CEO Christian Ulbrich is leading the geographic expansion strategy.",
      status: "contacted",
      tags: ["Market Expansion", "CRE", "Sun Belt"],
      aiScore: 78,
      dealValue: 95000,
      source: "JLL Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "Cushman & Wakefield",
      website: "cushmanwakefield.com",
      contactName: "Michelle MacKay",
      title: "CEO",
      email: "michelle.mackay@cushwake.com",
      triggerEvent: "Closed 12 transactions last quarter — record Q3",
      intelligenceSummary: "Cushman & Wakefield had a record-breaking quarter with 12 major transactions closed. CEO Michelle MacKay is investing in technology infrastructure to sustain this deal velocity. CRM and pipeline management tools are top of mind.",
      status: "qualified",
      tags: ["Record Q3", "CRE", "Pipeline Growth"],
      aiScore: 80,
      dealValue: 85000,
      source: "Cushman Earnings Report",
      updatedAt: NOW,
    },
    {
      companyName: "Colliers International",
      website: "colliers.com",
      contactName: "Jay Hennick",
      title: "Chairman & CEO",
      email: "jay.hennick@colliers.com",
      phone: "+1 (416) 555-0303",
      triggerEvent: "Acquired 3 boutique firms — integration underway",
      intelligenceSummary: "Colliers is integrating three recent boutique acquisitions across North America. Chairman Jay Hennick is prioritizing technology consolidation to unify the acquired firms onto a single platform. Strong integration vendor opportunity.",
      status: "new",
      tags: ["M&A Integration", "CRE", "Platform Consolidation"],
      aiScore: 75,
      dealValue: 100000,
      source: "Globe & Mail",
      updatedAt: NOW,
    },
    {
      companyName: "Marcus & Millichap",
      website: "marcusmillichap.com",
      contactName: "Hessam Nadji",
      title: "President & CEO",
      email: "hessam.nadji@marcusmillichap.com",
      triggerEvent: "Expanding brokerage network — 30 new agents in Q4",
      intelligenceSummary: "Marcus & Millichap is in a strong growth phase with significant agent additions. CEO Hessam Nadji is focused on scaling the technology infrastructure to support the larger team. Opportunity for CRM and commission management software.",
      status: "new",
      tags: ["Agent Expansion", "Brokerage", "Investment RE"],
      aiScore: 68,
      dealValue: 55000,
      source: "M&M Investor Relations",
      updatedAt: NOW,
    },
    {
      companyName: "Keller Williams",
      website: "kellerwilliams.com",
      contactName: "Mark Willis",
      title: "CEO",
      email: "mark.willis@kw.com",
      phone: "+1 (512) 555-0304",
      triggerEvent: "Launched KWIQ AI assistant — evaluating data vendor partnerships",
      intelligenceSummary: "Keller Williams' proprietary AI assistant KWIQ is requiring new data vendor integrations. CEO Mark Willis is overseeing the technology ecosystem review for KW's massive agent network. Major platform integration opportunity.",
      status: "contacted",
      tags: ["AI Launch", "Residential RE", "Agent Network"],
      aiScore: 72,
      dealValue: 200000,
      source: "Inman News",
      updatedAt: NOW,
    },
    {
      companyName: "RE/MAX",
      website: "remax.com",
      contactName: "Nick Bailey",
      title: "President & CEO",
      email: "nick.bailey@remax.com",
      triggerEvent: "Digital transformation initiative — replacing legacy systems",
      intelligenceSummary: "RE/MAX is undergoing a full digital transformation, replacing legacy systems across its franchise network. CEO Nick Bailey has made technology modernization a centerpiece of the company's 5-year plan. Greenfield vendor opportunity.",
      status: "qualified",
      tags: ["Digital Transformation", "Franchise Network", "Legacy Replacement"],
      aiScore: 76,
      dealValue: 160000,
      source: "RE/MAX Annual Report",
      updatedAt: NOW,
    },
    {
      companyName: "Savills",
      website: "savills.com",
      contactName: "Mark Ridley",
      title: "Group CEO",
      email: "mark.ridley@savills.com",
      phone: "+44 20 555 0305",
      triggerEvent: "US expansion — opening 5 new North American offices",
      intelligenceSummary: "Savills is making a significant US market push with five new offices. Group CEO Mark Ridley is leading the North American expansion and requires localized technology partnerships. Excellent timing for US-based vendor outreach.",
      status: "new",
      tags: ["US Expansion", "International CRE", "Luxury RE"],
      aiScore: 70,
      dealValue: 90000,
      source: "Estates Gazette",
      updatedAt: NOW,
    },
    {
      companyName: "Eastdil Secured",
      website: "eastdilsecured.com",
      contactName: "Roy March",
      title: "CEO",
      email: "roy.march@eastdilsecured.com",
      triggerEvent: "Led $2B hotel portfolio sale — largest since pandemic",
      intelligenceSummary: "Eastdil Secured executed the largest hospitality portfolio sale since 2020. CEO Roy March is evaluating deal management technology to handle the scale of complex multi-asset transactions. Strong capital markets software opportunity.",
      status: "new",
      tags: ["Capital Markets", "Hospitality", "Large Deal Flow"],
      aiScore: 83,
      dealValue: 110000,
      source: "Real Estate Alert",
      updatedAt: NOW,
    },
    {
      companyName: "Newmark",
      website: "nmrk.com",
      contactName: "Barry Gosin",
      title: "CEO",
      email: "barry.gosin@nmrk.com",
      phone: "+1 (212) 555-0306",
      triggerEvent: "IPO'd in 2021 — scaling corporate structure and tech infrastructure",
      intelligenceSummary: "Newmark went public and is investing in corporate-grade technology infrastructure to meet public company reporting requirements. CEO Barry Gosin is sponsoring the enterprise technology stack buildout.",
      status: "proposal",
      tags: ["Public Company", "CRE", "Post-IPO Scaling"],
      aiScore: 79,
      dealValue: 130000,
      source: "SEC Filing",
      updatedAt: NOW,
    },
    {
      companyName: "Walker & Dunlop",
      website: "walkerdunlop.com",
      contactName: "Willy Walker",
      title: "Chairman & CEO",
      email: "willy.walker@walkerdunlop.com",
      triggerEvent: "Launched technology division — acquired GeoPhy analytics platform",
      intelligenceSummary: "Walker & Dunlop acquired GeoPhy, signaling a major investment in data-driven CRE finance. Chairman Willy Walker is building an integrated technology stack for multifamily lending. Strategic partner for fintech and proptech vendors.",
      status: "qualified",
      tags: ["CRE Finance", "Proptech", "Multifamily"],
      aiScore: 85,
      dealValue: 145000,
      source: "GlobeSt",
      updatedAt: NOW,
    },
    {
      companyName: "Coldwell Banker Commercial",
      website: "cbcworldwide.com",
      contactName: "David Marine",
      title: "Chief Marketing Officer",
      email: "david.marine@coldwellbanker.com",
      phone: "+1 (800) 555-0307",
      triggerEvent: "National rebrand campaign — evaluating MarTech stack",
      intelligenceSummary: "Coldwell Banker Commercial is running a national rebrand alongside a full MarTech stack review. CMO David Marine is leading vendor selection for digital marketing, CRM, and lead generation platforms.",
      status: "new",
      tags: ["Rebrand", "MarTech Review", "National Franchise"],
      aiScore: 62,
      dealValue: 75000,
      source: "MediaPost",
      updatedAt: NOW,
    },
  ],

  finance: [
    {
      companyName: "Plaid",
      website: "plaid.com",
      contactName: "Zach Perret",
      title: "CEO & Co-founder",
      email: "zach.perret@plaid.com",
      phone: "+1 (415) 555-0401",
      triggerEvent: "Processing $2B+ in annual transaction volume",
      intelligenceSummary: "Plaid's API platform now processes over $2B in annual transactions. CEO Zach Perret is building the enterprise sales motion to capture large FI clients. Excellent fit for compliance, data, and security tooling.",
      status: "qualified",
      tags: ["Open Banking", "API Platform", "Series D"],
      aiScore: 92,
      dealValue: 130000,
      source: "Plaid Blog",
      updatedAt: NOW,
    },
    {
      companyName: "Brex",
      website: "brex.com",
      contactName: "Henrique Dubugras",
      title: "CEO & Co-founder",
      email: "henrique@brex.com",
      phone: "+1 (415) 555-0402",
      triggerEvent: "Launched new credit product for enterprise clients",
      intelligenceSummary: "Brex is expanding from startup-focused cards to enterprise spend management. CEO Henrique Dubugras is targeting Fortune 500 treasury teams. New product launch creates opportunity for complementary fintech tooling.",
      status: "new",
      tags: ["Corporate Cards", "Enterprise Pivot", "Fintech"],
      aiScore: 88,
      dealValue: 110000,
      source: "Bloomberg",
      updatedAt: NOW,
    },
    {
      companyName: "Ramp",
      website: "ramp.com",
      contactName: "Eric Glyman",
      title: "CEO & Co-founder",
      email: "eric.glyman@ramp.com",
      triggerEvent: "Reached $10B valuation — fastest growing fintech",
      intelligenceSummary: "Ramp hit a $10B valuation with exceptional growth metrics. CEO Eric Glyman is aggressively building the enterprise sales team and technology ecosystem. Strategic opportunity for ERP integration and financial data vendors.",
      status: "contacted",
      tags: ["Spend Management", "High Growth", "Fintech Unicorn"],
      aiScore: 90,
      dealValue: 95000,
      source: "The Information",
      updatedAt: NOW,
    },
    {
      companyName: "Carta",
      website: "carta.com",
      contactName: "Henry Ward",
      title: "CEO",
      email: "henry.ward@carta.com",
      phone: "+1 (650) 555-0403",
      triggerEvent: "Expanded banking license — launching venture debt product",
      intelligenceSummary: "Carta is expanding beyond cap table management into venture banking. CEO Henry Ward is building the technology infrastructure for the new lending product. Strong fit for compliance, risk, and lending software vendors.",
      status: "new",
      tags: ["Cap Table", "Venture Banking", "Expanding License"],
      aiScore: 85,
      dealValue: 120000,
      source: "Forbes",
      updatedAt: NOW,
    },
    {
      companyName: "Rippling",
      website: "rippling.com",
      contactName: "Parker Conrad",
      title: "CEO & Co-founder",
      email: "parker@rippling.com",
      phone: "+1 (415) 555-0404",
      triggerEvent: "Series F at $13.4B valuation — building global payroll",
      intelligenceSummary: "Rippling's latest funding round at $13.4B values it as one of the top HR/fintech companies. CEO Parker Conrad is building out global payroll capabilities requiring international banking and compliance partnerships.",
      status: "new",
      tags: ["HR-Fintech", "Global Payroll", "Series F"],
      aiScore: 91,
      dealValue: 200000,
      source: "TechCrunch",
      updatedAt: NOW,
    },
    {
      companyName: "Gusto",
      website: "gusto.com",
      contactName: "Tomer London",
      title: "Co-founder & Chief Product Officer",
      email: "tomer@gusto.com",
      triggerEvent: "Launched Gusto Embedded Payroll — new B2B channel",
      intelligenceSummary: "Gusto's Embedded Payroll product opens a new B2B channel targeting HR software vendors. CPO Tomer London is building the partner ecosystem for this embedded finance play. Strong integration partnership opportunity.",
      status: "qualified",
      tags: ["Embedded Finance", "Payroll", "B2B Channel"],
      aiScore: 83,
      dealValue: 85000,
      source: "Gusto Blog",
      updatedAt: NOW,
    },
    {
      companyName: "Adyen",
      website: "adyen.com",
      contactName: "Ingo Uytdehaage",
      title: "Co-CEO",
      email: "ingo.uytdehaage@adyen.com",
      phone: "+31 20 555 0405",
      triggerEvent: "US market expansion — opening Chicago and Dallas offices",
      intelligenceSummary: "Adyen is doubling down on US market presence with new offices in Chicago and Dallas. Co-CEO Ingo Uytdehaage is overseeing US partner relationships. Strong opportunity for payment adjacent software vendors.",
      status: "new",
      tags: ["Payment Processing", "US Expansion", "Enterprise Payments"],
      aiScore: 78,
      dealValue: 160000,
      source: "Reuters",
      updatedAt: NOW,
    },
    {
      companyName: "Marqeta",
      website: "marqeta.com",
      contactName: "Simon Khalaf",
      title: "CEO",
      email: "simon.khalaf@marqeta.com",
      triggerEvent: "Won Goldman Sachs Marcus card program — major enterprise win",
      intelligenceSummary: "Marqeta won the Goldman Sachs Marcus card issuing program, marking a major enterprise milestone. CEO Simon Khalaf is expanding the enterprise sales and partnerships team to capitalize on the momentum.",
      status: "contacted",
      tags: ["Card Issuing", "Enterprise Win", "Fintech"],
      aiScore: 87,
      dealValue: 140000,
      source: "Marqeta Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "Affirm",
      website: "affirm.com",
      contactName: "Max Levchin",
      title: "CEO & Founder",
      email: "max.levchin@affirm.com",
      phone: "+1 (415) 555-0406",
      triggerEvent: "Launched Affirm Card — expanding to physical commerce",
      intelligenceSummary: "Affirm's physical debit card launch expands its BNPL reach into brick-and-mortar retail. CEO Max Levchin is building vendor partnerships to support the omnichannel payment infrastructure.",
      status: "new",
      tags: ["BNPL", "Physical Commerce", "Debit Card"],
      aiScore: 80,
      dealValue: 115000,
      source: "WSJ",
      updatedAt: NOW,
    },
    {
      companyName: "Blend",
      website: "blend.com",
      contactName: "Nima Ghamsari",
      title: "CEO & Co-founder",
      email: "nima.ghamsari@blend.com",
      triggerEvent: "Partnered with 330+ banks — mortgage tech market leader",
      intelligenceSummary: "Blend powers mortgage applications for over 330 banks and lenders. CEO Nima Ghamsari is expanding into home equity and deposit accounts. Strategic partner for data, compliance, and document management vendors.",
      status: "qualified",
      tags: ["Mortgage Tech", "Banking Partner", "Proptech-Fintech"],
      aiScore: 82,
      dealValue: 100000,
      source: "HousingWire",
      updatedAt: NOW,
    },
    {
      companyName: "Betterment",
      website: "betterment.com",
      contactName: "Sarah Levy",
      title: "CEO",
      email: "sarah.levy@betterment.com",
      phone: "+1 (212) 555-0407",
      triggerEvent: "Launched Betterment for Advisors — B2B expansion",
      intelligenceSummary: "Betterment is expanding beyond retail investors to target RIAs with its advisor platform. CEO Sarah Levy is building the B2B sales motion and evaluating technology partnerships for the advisor ecosystem.",
      status: "new",
      tags: ["Robo-Advisory", "RIA Channel", "B2B Expansion"],
      aiScore: 75,
      dealValue: 70000,
      source: "Financial Planning",
      updatedAt: NOW,
    },
    {
      companyName: "Wealthfront",
      website: "wealthfront.com",
      contactName: "David Fortunato",
      title: "CEO",
      email: "david.fortunato@wealthfront.com",
      triggerEvent: "Acquisition by UBS called off — independence strategy reboot",
      intelligenceSummary: "Wealthfront's cancelled UBS acquisition is driving an independent growth strategy under CEO David Fortunato. The company is investing in technology and vendor partnerships to accelerate organic growth.",
      status: "new",
      tags: ["Robo-Advisory", "Post-M&A", "Independent Strategy"],
      aiScore: 72,
      dealValue: 80000,
      source: "Bloomberg",
      updatedAt: NOW,
    },
  ],

  healthcare: [
    {
      companyName: "Teladoc Health",
      website: "teladoc.com",
      contactName: "Jason Gorevic",
      title: "CEO",
      email: "jason.gorevic@teladoc.com",
      phone: "+1 (203) 555-0501",
      triggerEvent: "Expanding provider network to 15,000 physicians",
      intelligenceSummary: "Teladoc is scaling its provider network with a goal of 15,000 credentialed physicians. CEO Jason Gorevic is overseeing the credentialing and provider management technology stack review. Strong healthcare IT opportunity.",
      status: "new",
      tags: ["Telehealth", "Provider Network", "Scale-Up"],
      aiScore: 82,
      dealValue: 130000,
      source: "Teladoc Investor Relations",
      updatedAt: NOW,
    },
    {
      companyName: "Hims & Hers Health",
      website: "forhims.com",
      contactName: "Andrew Dudum",
      title: "CEO & Co-founder",
      email: "andrew.dudum@forhims.com",
      phone: "+1 (415) 555-0502",
      triggerEvent: "Received FDA clearance for new weight loss therapy",
      intelligenceSummary: "Hims & Hers received FDA clearance for a new weight loss program, creating a significant new revenue vertical. CEO Andrew Dudum is building the operations and vendor ecosystem to launch at scale.",
      status: "contacted",
      tags: ["FDA Clearance", "DTC Health", "New Program"],
      aiScore: 79,
      dealValue: 85000,
      source: "FDA.gov",
      updatedAt: NOW,
    },
    {
      companyName: "Oscar Health",
      website: "hioscar.com",
      contactName: "Mark Bertolini",
      title: "CEO",
      email: "mark.bertolini@hioscar.com",
      phone: "+1 (646) 555-0503",
      triggerEvent: "Expanding to 18 states — new market launches",
      intelligenceSummary: "Oscar Health is entering 5 new states this enrollment period. CEO Mark Bertolini is overseeing the technology and operations buildout for each new market. Opportunity for market-entry analytics and healthcare ops tooling.",
      status: "new",
      tags: ["Insurance", "Market Expansion", "ACA"],
      aiScore: 76,
      dealValue: 100000,
      source: "Modern Healthcare",
      updatedAt: NOW,
    },
    {
      companyName: "Devoted Health",
      website: "devoted.com",
      contactName: "Todd Park",
      title: "CEO & Co-founder",
      email: "todd.park@devoted.com",
      triggerEvent: "Launched new care program — integrated home health model",
      intelligenceSummary: "Devoted Health launched an integrated home health program targeting Medicare Advantage members. CEO Todd Park is building the care coordination technology stack. Strong opportunity for home health software and analytics vendors.",
      status: "qualified",
      tags: ["Medicare Advantage", "Home Health", "Care Coordination"],
      aiScore: 83,
      dealValue: 115000,
      source: "STAT News",
      updatedAt: NOW,
    },
    {
      companyName: "Accolade",
      website: "accolade.com",
      contactName: "Rajeev Singh",
      title: "CEO",
      email: "rajeev.singh@accolade.com",
      phone: "+1 (206) 555-0504",
      triggerEvent: "Won 40 new employer clients in Q3 — record bookings",
      intelligenceSummary: "Accolade had its best enterprise bookings quarter with 40 new employer clients. CEO Rajeev Singh is scaling the operations team and vendor stack to support rapid growth. Excellent fit for enterprise healthcare ops tooling.",
      status: "new",
      tags: ["Health Navigation", "Employer Market", "Record Bookings"],
      aiScore: 81,
      dealValue: 95000,
      source: "Accolade Earnings",
      updatedAt: NOW,
    },
    {
      companyName: "Omada Health",
      website: "omadahealth.com",
      contactName: "Sean Duffy",
      title: "CEO & Co-founder",
      email: "sean.duffy@omadahealth.com",
      triggerEvent: "Secured $192M Series E — scaling diabetes prevention",
      intelligenceSummary: "Omada Health's $192M Series E positions it to scale its digital diabetes prevention programs nationally. CEO Sean Duffy is expanding payer partnerships and vendor relationships for the clinical technology stack.",
      status: "contacted",
      tags: ["Digital Health", "Chronic Disease", "Series E"],
      aiScore: 85,
      dealValue: 90000,
      source: "Rock Health",
      updatedAt: NOW,
    },
    {
      companyName: "Cityblock Health",
      website: "cityblock.com",
      contactName: "Toyin Ajayi",
      title: "CEO & Co-founder",
      email: "toyin.ajayi@cityblock.com",
      phone: "+1 (718) 555-0505",
      triggerEvent: "Expanded to 10 cities — community health centers opening",
      intelligenceSummary: "Cityblock Health is opening community health centers across 10 cities focused on underserved populations. CEO Toyin Ajayi is managing rapid operational expansion requiring care coordination and health equity technology partners.",
      status: "new",
      tags: ["Community Health", "Social Determinants", "Expansion"],
      aiScore: 72,
      dealValue: 75000,
      source: "Healthcare Dive",
      updatedAt: NOW,
    },
    {
      companyName: "Alignment Healthcare",
      website: "alignmenthealthcare.com",
      contactName: "John Kao",
      title: "CEO",
      email: "john.kao@alignmenthealthcare.com",
      triggerEvent: "IPO'd on NASDAQ — using proceeds for technology buildout",
      intelligenceSummary: "Alignment Healthcare went public and is deploying IPO proceeds into its AVA technology platform. CEO John Kao is overseeing vendor partnerships for the next generation of their care enablement platform.",
      status: "qualified",
      tags: ["Medicare Advantage", "Post-IPO", "Care Enablement"],
      aiScore: 80,
      dealValue: 120000,
      source: "SEC S-1",
      updatedAt: NOW,
    },
    {
      companyName: "Bright Health",
      website: "brighthealthgroup.com",
      contactName: "Mike Mikan",
      title: "CEO",
      email: "mike.mikan@brighthealthgroup.com",
      phone: "+1 (612) 555-0506",
      triggerEvent: "Refocusing on Care Delivery — divesting insurance segments",
      intelligenceSummary: "Bright Health is strategically pivoting to pure care delivery after divesting insurance assets. CEO Mike Mikan is rebuilding the technology stack around the care delivery model. Major vendor opportunity during restructuring.",
      status: "new",
      tags: ["Strategic Pivot", "Care Delivery", "Restructuring"],
      aiScore: 65,
      dealValue: 80000,
      source: "Modern Healthcare",
      updatedAt: NOW,
    },
    {
      companyName: "Privia Health",
      website: "priviahealth.com",
      contactName: "Parth Mehrotra",
      title: "CEO",
      email: "parth.mehrotra@priviahealth.com",
      triggerEvent: "Added 1,200 physicians in Q4 — rapid network growth",
      intelligenceSummary: "Privia Health added over 1,200 physicians in its last quarter alone. CEO Parth Mehrotra is scaling the technology platform to manage the rapid network growth, creating strong demand for provider management tooling.",
      status: "new",
      tags: ["Physician Network", "Value-Based Care", "Growth Stage"],
      aiScore: 78,
      dealValue: 100000,
      source: "Privia Investor Relations",
      updatedAt: NOW,
    },
    {
      companyName: "Livongo (Teladoc)",
      website: "livongo.com",
      contactName: "Glen Tullman",
      title: "Executive Chairman",
      email: "glen.tullman@livongo.com",
      phone: "+1 (773) 555-0507",
      triggerEvent: "Re-launching consumer chronic condition platform post-integration",
      intelligenceSummary: "The Livongo brand is being re-energized within Teladoc's consumer health portfolio. Executive Chairman Glen Tullman is advising on vendor partnerships for the refreshed platform targeting chronic condition management.",
      status: "contacted",
      tags: ["Chronic Care", "Digital Health", "Re-Launch"],
      aiScore: 70,
      dealValue: 85000,
      source: "Healthcare IT News",
      updatedAt: NOW,
    },
    {
      companyName: "Nana Health",
      website: "nanahealth.com",
      contactName: "Demetrius Drax",
      title: "VP Clinical Operations",
      email: "demetrius.drax@nanahealth.com",
      triggerEvent: "Launched new home care program targeting elderly patients",
      intelligenceSummary: "Nana Health's home care expansion is targeting the rapidly growing elderly patient segment. VP Clinical Operations Demetrius Drax is leading vendor selection for clinical documentation and care coordination tools.",
      status: "new",
      tags: ["Home Care", "Senior Health", "New Program"],
      aiScore: 67,
      dealValue: 55000,
      source: "Home Health Care News",
      updatedAt: NOW,
    },
  ],

  ecommerce: [
    {
      companyName: "Shopify",
      website: "shopify.com",
      contactName: "Harley Finkelstein",
      title: "President",
      email: "harley.finkelstein@shopify.com",
      phone: "+1 (613) 555-0601",
      triggerEvent: "Scaled to $7B GMV per month — accelerating partner ecosystem",
      intelligenceSummary: "Shopify's GMV continues to set records, and President Harley Finkelstein is aggressively growing the app ecosystem. Strong opportunity for Shopify-adjacent vendors across fulfillment, analytics, and marketing.",
      status: "qualified",
      tags: ["Commerce Platform", "App Ecosystem", "Enterprise"],
      aiScore: 88,
      dealValue: 250000,
      source: "Shopify Earnings",
      updatedAt: NOW,
    },
    {
      companyName: "Klaviyo",
      website: "klaviyo.com",
      contactName: "Andrew Bialecki",
      title: "CEO & Co-founder",
      email: "andrew.bialecki@klaviyo.com",
      phone: "+1 (617) 555-0602",
      triggerEvent: "IPO'd on NYSE — $9B valuation at debut",
      intelligenceSummary: "Klaviyo went public in a landmark ecommerce tech IPO. CEO Andrew Bialecki is investing IPO proceeds into product expansion and vendor partnerships. Perfect timing for complementary MarTech vendors to engage.",
      status: "new",
      tags: ["Email Marketing", "Post-IPO", "Ecommerce MarTech"],
      aiScore: 90,
      dealValue: 140000,
      source: "NYSE",
      updatedAt: NOW,
    },
    {
      companyName: "Gorgias",
      website: "gorgias.com",
      contactName: "Romain Lapeyre",
      title: "CEO & Co-founder",
      email: "romain.lapeyre@gorgias.com",
      triggerEvent: "Scaled to $10M ARR — expanding into enterprise tier",
      intelligenceSummary: "Gorgias hit $10M ARR and is moving upmarket to capture enterprise ecommerce brands. CEO Romain Lapeyre is building the enterprise sales motion and evaluating tooling partners for the new tier.",
      status: "contacted",
      tags: ["Customer Support", "Ecommerce CX", "Enterprise Pivot"],
      aiScore: 82,
      dealValue: 75000,
      source: "SaaStr",
      updatedAt: NOW,
    },
    {
      companyName: "Yotpo",
      website: "yotpo.com",
      contactName: "Tomer Tagrin",
      title: "CEO & Co-founder",
      email: "tomer.tagrin@yotpo.com",
      phone: "+1 (646) 555-0603",
      triggerEvent: "Launched loyalty and referral platform — expanding product suite",
      intelligenceSummary: "Yotpo expanded from reviews to a full customer loyalty platform. CEO Tomer Tagrin is building the partner ecosystem around the expanded suite. Strong opportunity for ecommerce analytics and SMS marketing integrations.",
      status: "new",
      tags: ["Reviews", "Loyalty Platform", "Ecommerce SaaS"],
      aiScore: 80,
      dealValue: 85000,
      source: "Yotpo Blog",
      updatedAt: NOW,
    },
    {
      companyName: "Attentive",
      website: "attentive.com",
      contactName: "Brian Long",
      title: "CEO & Co-founder",
      email: "brian.long@attentive.com",
      triggerEvent: "Reached $500M ARR — Series E at $10B valuation",
      intelligenceSummary: "Attentive's explosive SMS marketing growth has made it a top ecommerce MarTech platform. CEO Brian Long is investing in product integrations to deepen the platform ecosystem. High-value partner opportunity.",
      status: "new",
      tags: ["SMS Marketing", "Series E", "High Growth"],
      aiScore: 92,
      dealValue: 160000,
      source: "Forbes",
      updatedAt: NOW,
    },
    {
      companyName: "Loop Returns",
      website: "loopreturns.com",
      contactName: "Jonathan Poma",
      title: "CEO",
      email: "jonathan.poma@loopreturns.com",
      phone: "+1 (614) 555-0604",
      triggerEvent: "Launched mobile app — expanded to EU markets",
      intelligenceSummary: "Loop Returns launched a consumer-facing mobile app and expanded to Europe, creating new infrastructure needs. CEO Jonathan Poma is evaluating vendor partnerships for the EU compliance and localization stack.",
      status: "qualified",
      tags: ["Returns Management", "EU Expansion", "Mobile Launch"],
      aiScore: 78,
      dealValue: 65000,
      source: "Loop Blog",
      updatedAt: NOW,
    },
    {
      companyName: "ReCharge Payments",
      website: "rechargepayments.com",
      contactName: "Oisin O'Connor",
      title: "CEO & Co-founder",
      email: "oisin@rechargepayments.com",
      triggerEvent: "Added 15,000 new merchants in Q2 — subscription commerce leader",
      intelligenceSummary: "ReCharge added 15,000 merchants in a single quarter, cementing its position as the top Shopify subscription solution. CEO Oisin O'Connor is building integrations to serve larger enterprise merchants. Strong partner opportunity.",
      status: "new",
      tags: ["Subscription Commerce", "Shopify", "Merchant Growth"],
      aiScore: 83,
      dealValue: 90000,
      source: "ReCharge Blog",
      updatedAt: NOW,
    },
    {
      companyName: "Nacelle",
      website: "nacelle.com",
      contactName: "Brian Anderson",
      title: "CEO & Co-founder",
      email: "brian.anderson@nacelle.com",
      phone: "+1 (323) 555-0605",
      triggerEvent: "Launched headless commerce platform — $50M Series B",
      intelligenceSummary: "Nacelle's $50M Series B will fund its headless commerce platform expansion. CEO Brian Anderson is building the technology partner ecosystem for enterprise merchants adopting composable commerce. Excellent integration opportunity.",
      status: "contacted",
      tags: ["Headless Commerce", "Series B", "Composable"],
      aiScore: 85,
      dealValue: 95000,
      source: "Crunchbase",
      updatedAt: NOW,
    },
    {
      companyName: "Tapcart",
      website: "tapcart.com",
      contactName: "Eric Netsch",
      title: "CEO & Co-founder",
      email: "eric.netsch@tapcart.com",
      triggerEvent: "Crossed 50M mobile app installs for Shopify brands",
      intelligenceSummary: "Tapcart powers mobile apps for over 50M consumer installs across Shopify brands. CEO Eric Netsch is expanding the platform's push notification and loyalty capabilities. Strong fit for mobile analytics and personalization vendors.",
      status: "new",
      tags: ["Mobile Commerce", "Shopify", "App Platform"],
      aiScore: 76,
      dealValue: 60000,
      source: "Tapcart Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "Ordergroove",
      website: "ordergroove.com",
      contactName: "Greg Alvo",
      title: "CEO",
      email: "greg.alvo@ordergroove.com",
      phone: "+1 (646) 555-0606",
      triggerEvent: "Won 5 enterprise retail accounts — Target, PetSmart included",
      intelligenceSummary: "Ordergroove secured major enterprise retail clients including Target and PetSmart for its subscription and loyalty platform. CEO Greg Alvo is building out the enterprise customer success and vendor ecosystem.",
      status: "proposal",
      tags: ["Subscription Retail", "Enterprise Wins", "Loyalty"],
      aiScore: 87,
      dealValue: 110000,
      source: "Ordergroove Blog",
      updatedAt: NOW,
    },
    {
      companyName: "BigCommerce",
      website: "bigcommerce.com",
      contactName: "Brent Bellm",
      title: "CEO",
      email: "brent.bellm@bigcommerce.com",
      triggerEvent: "Partnered with Google Shopping — driving 30% merchant growth",
      intelligenceSummary: "BigCommerce's Google Shopping integration has driven significant new merchant acquisition. CEO Brent Bellm is expanding the app ecosystem to support the larger merchant base. Partner ecosystem is actively growing.",
      status: "new",
      tags: ["Ecommerce Platform", "Google Partner", "Merchant Growth"],
      aiScore: 74,
      dealValue: 80000,
      source: "BigCommerce Investor Relations",
      updatedAt: NOW,
    },
    {
      companyName: "Postscript",
      website: "postscript.io",
      contactName: "Adam Turner",
      title: "CEO & Co-founder",
      email: "adam.turner@postscript.io",
      phone: "+1 (720) 555-0607",
      triggerEvent: "Launched Postscript Sales — new conversational SMS sales team",
      intelligenceSummary: "Postscript expanded beyond marketing into conversational SMS sales, requiring new AI and conversation analytics tooling. CEO Adam Turner is evaluating vendor integrations for the new Sales product layer.",
      status: "contacted",
      tags: ["SMS Commerce", "Conversational Sales", "New Product"],
      aiScore: 80,
      dealValue: 70000,
      source: "Postscript Blog",
      updatedAt: NOW,
    },
  ],

  manufacturing: [
    {
      companyName: "Xometry",
      website: "xometry.com",
      contactName: "Randy Altschuler",
      title: "CEO",
      email: "randy.altschuler@xometry.com",
      phone: "+1 (800) 555-0701",
      triggerEvent: "Expanding production capacity 30% — new supplier network",
      intelligenceSummary: "Xometry is scaling its manufacturing marketplace with a 30% capacity expansion. CEO Randy Altschuler is building the supplier onboarding and quality management vendor ecosystem. Strong opportunity for supply chain software.",
      status: "new",
      tags: ["Manufacturing Marketplace", "On-Demand MFG", "Capacity Expansion"],
      aiScore: 78,
      dealValue: 90000,
      source: "Xometry Investor Relations",
      updatedAt: NOW,
    },
    {
      companyName: "Fictiv",
      website: "fictiv.com",
      contactName: "Dave Evans",
      title: "CEO & Co-founder",
      email: "dave.evans@fictiv.com",
      phone: "+1 (415) 555-0702",
      triggerEvent: "Switching to just-in-time manufacturing model — vendor review",
      intelligenceSummary: "Fictiv is transitioning to a just-in-time model across its manufacturing network. CEO Dave Evans is evaluating ERP and supply chain vendor partnerships to enable real-time production visibility. JIT transition creates strong vendor opportunity.",
      status: "contacted",
      tags: ["On-Demand MFG", "JIT Model", "Digital Factory"],
      aiScore: 72,
      dealValue: 75000,
      source: "Manufacturing Dive",
      updatedAt: NOW,
    },
    {
      companyName: "Proto Labs",
      website: "protolabs.com",
      contactName: "Rob Bodor",
      title: "President & CEO",
      email: "rob.bodor@protolabs.com",
      triggerEvent: "New ISO 9001 certification — expanding quality programs",
      intelligenceSummary: "Proto Labs achieved new ISO certifications and is expanding its quality management infrastructure. CEO Rob Bodor is investing in quality and compliance software to support the expanded certification scope.",
      status: "new",
      tags: ["Rapid Prototyping", "ISO 9001", "Quality Systems"],
      aiScore: 68,
      dealValue: 60000,
      source: "Business Wire",
      updatedAt: NOW,
    },
    {
      companyName: "Markforged",
      website: "markforged.com",
      contactName: "Shai Terem",
      title: "President & CEO",
      email: "shai.terem@markforged.com",
      phone: "+1 (617) 555-0703",
      triggerEvent: "Launched Digital Forge platform — factory digitization push",
      intelligenceSummary: "Markforged's Digital Forge platform connects 3D printers across factory floors. CEO Shai Terem is building the vendor ecosystem for the platform's IoT and analytics layer. Strong opportunity for manufacturing data vendors.",
      status: "qualified",
      tags: ["3D Printing", "Factory Digitization", "IoT"],
      aiScore: 75,
      dealValue: 80000,
      source: "3D Printing Industry",
      updatedAt: NOW,
    },
    {
      companyName: "Desktop Metal",
      website: "desktopmetal.com",
      contactName: "Ric Fulop",
      title: "CEO & Co-founder",
      email: "ric.fulop@desktopmetal.com",
      triggerEvent: "Merging with Stratasys — combined entity vendor review",
      intelligenceSummary: "Desktop Metal's Stratasys merger is creating the world's largest 3D printing company. CEO Ric Fulop is overseeing the combined technology stack review. Major vendor consolidation opportunity for manufacturing software.",
      status: "new",
      tags: ["Metal 3D Printing", "Merger", "Additive Manufacturing"],
      aiScore: 70,
      dealValue: 95000,
      source: "TechCrunch",
      updatedAt: NOW,
    },
    {
      companyName: "Azenta Life Sciences",
      website: "azenta.com",
      contactName: "Steve Schwartz",
      title: "President & CEO",
      email: "steve.schwartz@azenta.com",
      phone: "+1 (978) 555-0704",
      triggerEvent: "Spun off semiconductor division — focusing on life sciences manufacturing",
      intelligenceSummary: "Azenta completed its semiconductor spinoff and is now fully focused on life sciences sample management. CEO Steve Schwartz is investing in manufacturing technology for the pure-play life sciences business.",
      status: "new",
      tags: ["Life Sciences", "Post-Spinoff", "Sample Management"],
      aiScore: 65,
      dealValue: 70000,
      source: "Azenta Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "John Crane",
      website: "johncrane.com",
      contactName: "Alan Ferguson",
      title: "President",
      email: "alan.ferguson@johncrane.com",
      triggerEvent: "Digitizing service operations — predictive maintenance investment",
      intelligenceSummary: "John Crane is investing significantly in predictive maintenance technology for its rotating equipment service business. President Alan Ferguson is leading the digital transformation of field service operations.",
      status: "contacted",
      tags: ["Industrial Equipment", "Predictive Maintenance", "Field Service"],
      aiScore: 71,
      dealValue: 85000,
      source: "Smiths Group Annual Report",
      updatedAt: NOW,
    },
    {
      companyName: "Parker Hannifin (Filtration Division)",
      website: "parker.com",
      contactName: "Karen Williams",
      title: "VP Operations, Filtration",
      email: "karen.williams@parker.com",
      phone: "+1 (216) 555-0705",
      triggerEvent: "Launched IoT-connected filter monitoring system",
      intelligenceSummary: "Parker Hannifin's Filtration Division is rolling out IoT monitoring across its industrial filter lines. VP Karen Williams is evaluating data and analytics vendors to support the connected product platform.",
      status: "new",
      tags: ["Industrial Filtration", "IoT Product", "Connected Manufacturing"],
      aiScore: 67,
      dealValue: 75000,
      source: "Parker Investor Relations",
      updatedAt: NOW,
    },
    {
      companyName: "Roper Technologies",
      website: "ropertech.com",
      contactName: "Neil Hunn",
      title: "President & CEO",
      email: "neil.hunn@ropertech.com",
      triggerEvent: "Divesting industrial businesses — focusing on software portfolio",
      intelligenceSummary: "Roper Technologies is divesting its industrial assets to focus on software businesses. CEO Neil Hunn is overseeing the portfolio transformation and evaluating software vendor partnerships for the new focus areas.",
      status: "new",
      tags: ["Industrial Software", "Portfolio Transformation", "Divestitures"],
      aiScore: 73,
      dealValue: 110000,
      source: "Roper Technologies Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "CIRCOR International",
      website: "circor.com",
      contactName: "Scott Buckhout",
      title: "President & CEO",
      email: "scott.buckhout@circor.com",
      phone: "+1 (781) 555-0706",
      triggerEvent: "Taken private by KKR — operational improvement mandate",
      intelligenceSummary: "CIRCOR was taken private by KKR with a mandate for operational improvement. CEO Scott Buckhout is working with PE-backed operational consultants to evaluate technology upgrades. Classic PE operational improvement opportunity.",
      status: "qualified",
      tags: ["Industrial Valves", "Private Equity", "Operational Improvement"],
      aiScore: 76,
      dealValue: 90000,
      source: "KKR Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "Chart Industries",
      website: "chartindustries.com",
      contactName: "Jill Evanko",
      title: "President & CEO",
      email: "jill.evanko@chartindustries.com",
      triggerEvent: "Acquired Howden — doubling revenue to $3.5B",
      intelligenceSummary: "Chart Industries' Howden acquisition more than doubled its revenue. CEO Jill Evanko is overseeing the integration technology stack, including ERP consolidation and manufacturing operations tooling. Major integration vendor opportunity.",
      status: "new",
      tags: ["Industrial Equipment", "Post-Acquisition", "ERP Integration"],
      aiScore: 79,
      dealValue: 120000,
      source: "Business Wire",
      updatedAt: NOW,
    },
    {
      companyName: "Watts Water Technologies",
      website: "wattswater.com",
      contactName: "Robert Hau",
      title: "President & CEO",
      email: "robert.hau@wattswater.com",
      phone: "+1 (978) 555-0707",
      triggerEvent: "Smart water management initiative — IoT sensor rollout",
      intelligenceSummary: "Watts Water is launching a smart water management initiative across its commercial and residential product lines. CEO Robert Hau is evaluating IoT platform and data analytics vendors for the connected products initiative.",
      status: "new",
      tags: ["Water Technology", "IoT Sensors", "Smart Building"],
      aiScore: 68,
      dealValue: 80000,
      source: "Watts Water Annual Report",
      updatedAt: NOW,
    },
  ],

  other: [
    {
      companyName: "Canva",
      website: "canva.com",
      contactName: "Melanie Perkins",
      title: "CEO & Co-founder",
      email: "melanie.perkins@canva.com",
      phone: "+61 2 555 0801",
      triggerEvent: "Launched Canva Enterprise — targeting Fortune 500 design teams",
      intelligenceSummary: "Canva's enterprise tier launch opens a high-ACV market for design and creative tooling. CEO Melanie Perkins is personally leading the enterprise push. Strong opportunity for brand management and creative workflow vendors.",
      status: "new",
      tags: ["Design Tools", "Enterprise Launch", "Unicorn"],
      aiScore: 85,
      dealValue: 110000,
      source: "Canva Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "Duolingo",
      website: "duolingo.com",
      contactName: "Luis von Ahn",
      title: "CEO & Co-founder",
      email: "luis@duolingo.com",
      phone: "+1 (412) 555-0802",
      triggerEvent: "Crossed 500M registered users — monetization expansion",
      intelligenceSummary: "Duolingo's 500M user milestone is driving investment in new monetization tools and B2B offerings. CEO Luis von Ahn is evaluating enterprise education partnerships. Strong signal for EdTech and analytics vendors.",
      status: "contacted",
      tags: ["EdTech", "Consumer App", "Monetization"],
      aiScore: 72,
      dealValue: 85000,
      source: "Duolingo Investor Relations",
      updatedAt: NOW,
    },
    {
      companyName: "Coursera",
      website: "coursera.org",
      contactName: "Jeff Maggioncalda",
      title: "CEO",
      email: "jeff.maggioncalda@coursera.org",
      triggerEvent: "Signed 100 enterprise university partners — B2B expansion",
      intelligenceSummary: "Coursera for Business is growing rapidly with 100+ enterprise university content partners. CEO Jeff Maggioncalda is evaluating vendor partnerships for the enterprise LMS and analytics layer.",
      status: "new",
      tags: ["EdTech", "Enterprise Learning", "B2B"],
      aiScore: 76,
      dealValue: 90000,
      source: "Coursera Earnings",
      updatedAt: NOW,
    },
    {
      companyName: "Asana",
      website: "asana.com",
      contactName: "Dustin Moskovitz",
      title: "CEO & Co-founder",
      email: "dustin.moskovitz@asana.com",
      phone: "+1 (415) 555-0803",
      triggerEvent: "Launched AI Work Intelligence — positioning vs Microsoft Copilot",
      intelligenceSummary: "Asana's AI layer is being positioned as a Microsoft Copilot alternative for enterprise project management. CEO Dustin Moskovitz is evaluating technology partnerships for the AI platform ecosystem.",
      status: "qualified",
      tags: ["Project Management", "AI Features", "Enterprise"],
      aiScore: 82,
      dealValue: 95000,
      source: "Asana Blog",
      updatedAt: NOW,
    },
    {
      companyName: "Peloton",
      website: "onepeloton.com",
      contactName: "Chris Bruzzo",
      title: "Co-CEO",
      email: "chris.bruzzo@onepeloton.com",
      triggerEvent: "B2B corporate wellness push — targeting 500 enterprise clients",
      intelligenceSummary: "Peloton is pivoting to corporate wellness with an aggressive B2B target. Co-CEO Chris Bruzzo is overseeing the enterprise sales motion and evaluating vendor partnerships for the B2B platform.",
      status: "new",
      tags: ["Fitness Tech", "Corporate Wellness", "B2B Pivot"],
      aiScore: 65,
      dealValue: 70000,
      source: "WSJ",
      updatedAt: NOW,
    },
    {
      companyName: "Notion Calendar",
      website: "cron.com",
      contactName: "Raphael Schaad",
      title: "Co-founder",
      email: "raphael@cron.com",
      phone: "+1 (650) 555-0804",
      triggerEvent: "Acquired by Notion — integration roadmap being built",
      intelligenceSummary: "Cron's acquisition by Notion is triggering a full product integration. Co-founder Raphael Schaad is helping manage vendor relationships for the combined calendar and workspace product. Partnership opportunity for calendar and scheduling vendors.",
      status: "new",
      tags: ["Calendar App", "Notion Ecosystem", "Post-Acquisition"],
      aiScore: 70,
      dealValue: 50000,
      source: "TechCrunch",
      updatedAt: NOW,
    },
    {
      companyName: "OpenAI",
      website: "openai.com",
      contactName: "Sam Altman",
      title: "CEO",
      email: "sam.altman@openai.com",
      triggerEvent: "Launched ChatGPT Enterprise — targeting Fortune 500 deployments",
      intelligenceSummary: "OpenAI's enterprise tier is rapidly winning Fortune 500 contracts. CEO Sam Altman is building the vendor ecosystem for enterprise deployment, compliance, and integration. High-ACV opportunity for AI-adjacent vendors.",
      status: "new",
      tags: ["AI Platform", "Enterprise AI", "ChatGPT"],
      aiScore: 95,
      dealValue: 500000,
      source: "OpenAI Blog",
      updatedAt: NOW,
    },
    {
      companyName: "Navan (TripActions)",
      website: "navan.com",
      contactName: "Ariel Cohen",
      title: "CEO & Co-founder",
      email: "ariel.cohen@navan.com",
      phone: "+1 (650) 555-0805",
      triggerEvent: "Rebranded as Navan — launching integrated travel and expense",
      intelligenceSummary: "TripActions rebranded as Navan to signal its full travel-and-expense platform. CEO Ariel Cohen is building partner integrations for the expanded platform. Opportunity for ERP, finance, and HR systems integration.",
      status: "contacted",
      tags: ["Travel & Expense", "Rebrand", "Integrated Platform"],
      aiScore: 83,
      dealValue: 100000,
      source: "Navan Press Release",
      updatedAt: NOW,
    },
    {
      companyName: "ServiceTitan",
      website: "servicetitan.com",
      contactName: "Ara Mahdessian",
      title: "CEO & Co-founder",
      email: "ara.mahdessian@servicetitan.com",
      triggerEvent: "Filed for IPO — $7.6B valuation on $614M ARR",
      intelligenceSummary: "ServiceTitan filed for IPO with impressive ARR metrics for field service management. CEO Ara Mahdessian is building the technology ecosystem for public company readiness and post-IPO growth.",
      status: "new",
      tags: ["Field Service", "Pre-IPO", "SMB SaaS"],
      aiScore: 88,
      dealValue: 130000,
      source: "SEC S-1",
      updatedAt: NOW,
    },
    {
      companyName: "Databricks",
      website: "databricks.com",
      contactName: "Ali Ghodsi",
      title: "CEO & Co-founder",
      email: "ali.ghodsi@databricks.com",
      phone: "+1 (415) 555-0806",
      triggerEvent: "Raised $500M — $43B valuation, accelerating AI/data platform",
      intelligenceSummary: "Databricks' $500M raise at a $43B valuation reflects its dominance in enterprise data and AI. CEO Ali Ghodsi is expanding the vendor ecosystem for the Lakehouse platform. Strategic partner opportunity for data infrastructure vendors.",
      status: "qualified",
      tags: ["Data Platform", "AI/ML", "Series I"],
      aiScore: 93,
      dealValue: 250000,
      source: "TechCrunch",
      updatedAt: NOW,
    },
  ],
};

// ---------------------------------------------------------------------------
// POST /api/leads/seed
// ---------------------------------------------------------------------------

export async function POST(req: NextRequest) {
  try {
    const body = await req.json().catch(() => ({}));
    const industry: string = (body.industry ?? "other").toLowerCase();

    // ------------------------------------------------------------------
    // 1. Check if leads already exist
    // ------------------------------------------------------------------
    const { count, error: countError } = await supabase
      .from("Lead")
      .select("*", { count: "exact", head: true });

    if (countError) {
      console.error("[seed] count error:", countError);
      return NextResponse.json({ error: "Failed to check existing leads" }, { status: 500 });
    }

    if ((count ?? 0) > 0) {
      return NextResponse.json({ seeded: false, reason: "leads_exist", count });
    }

    // ------------------------------------------------------------------
    // 2. Select industry seed data (fallback to "other")
    // ------------------------------------------------------------------
    const leads: SeedLead[] = SEED_DATA[industry] ?? SEED_DATA["other"];

    // ------------------------------------------------------------------
    // 3. Insert seed leads
    // ------------------------------------------------------------------
    const { data: inserted, error: insertError } = await supabase
      .from("Lead")
      .insert(leads)
      .select();

    if (insertError) {
      console.error("[seed] insert error:", insertError);
      return NextResponse.json({ error: "Failed to insert seed leads", detail: insertError.message }, { status: 500 });
    }

    const insertedLeads = inserted ?? [];

    // ------------------------------------------------------------------
    // 4. Hunter.io enrichment (optional)
    // ------------------------------------------------------------------
    const hunterKey = process.env.HUNTER_IO_API_KEY;
    if (hunterKey && insertedLeads.length > 0) {
      const toEnrich = insertedLeads.slice(0, 5);
      await Promise.allSettled(
        toEnrich.map(async (lead: Record<string, unknown>) => {
          try {
            const domain = (lead.website as string | null)?.replace(/^https?:\/\//, "").split("/")[0];
            if (!domain || !lead.contactName) return;

            const nameParts = (lead.contactName as string).split(" ");
            const firstName = nameParts[0] ?? "";
            const lastName = nameParts[nameParts.length - 1] ?? "";

            const url = `https://api.hunter.io/v2/email-finder?domain=${encodeURIComponent(domain)}&first_name=${encodeURIComponent(firstName)}&last_name=${encodeURIComponent(lastName)}&api_key=${hunterKey}`;
            const res = await fetch(url, { cache: "no-store" });
            const data = await res.json();

            const email = data?.data?.email;
            const confidence = data?.data?.score ?? 0;

            if (email && confidence > 70 && lead.id) {
              await supabase
                .from("Lead")
                .update({ email })
                .eq("id", lead.id);
            }
          } catch (err) {
            console.warn("[seed] hunter enrichment failed for lead:", lead.id, err);
          }
        })
      );
    }

    // ------------------------------------------------------------------
    // 5. Apollo.io additional leads (optional)
    // ------------------------------------------------------------------
    const apolloKey = process.env.APOLLO_API_KEY;
    if (apolloKey) {
      try {
        const apolloRes = await fetch("https://api.apollo.io/v1/mixed_people/search", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": apolloKey,
          },
          body: JSON.stringify({
            person_titles: ["VP Sales", "Director of Business Development", "Head of Growth"],
            organization_industry_tag_ids: [],
            page: 1,
            per_page: 5,
          }),
          cache: "no-store",
        });

        if (apolloRes.ok) {
          const apolloData = await apolloRes.json();
          const people: Array<Record<string, unknown>> = apolloData?.people ?? [];

          const apolloLeads: SeedLead[] = people
            .filter((p) => p.email)
            .map((p) => {
              const orgName = (p.organization as Record<string, unknown> | null)?.name as string | undefined;
              const orgWebsite = (p.organization as Record<string, unknown> | null)?.website_url as string | undefined;
              return {
                companyName: orgName ?? "Unknown Company",
                website: orgWebsite ?? undefined,
                contactName: `${p.first_name ?? ""} ${p.last_name ?? ""}`.trim() || "Unknown Contact",
                title: (p.title as string) ?? "Contact",
                email: p.email as string,
                phone: (p.phone_numbers as Array<{ sanitized_number: string }> | null)?.[0]?.sanitized_number ?? undefined,
                triggerEvent: "Identified via Apollo.io people search",
                intelligenceSummary: `${orgName ?? "Company"} contact identified through Apollo intelligence data. Title: ${(p.title as string) ?? "N/A"}.`,
                status: "new",
                tags: ["Apollo", "Enriched"],
                source: "Apollo.io",
                updatedAt: NOW,
              };
            });

          if (apolloLeads.length > 0) {
            const { error: apolloInsertError } = await supabase
              .from("Lead")
              .insert(apolloLeads);

            if (apolloInsertError) {
              console.warn("[seed] Apollo insert error:", apolloInsertError);
            }
          }
        }
      } catch (err) {
        console.warn("[seed] Apollo enrichment failed:", err);
      }
    }

    return NextResponse.json({
      seeded: true,
      industry,
      count: insertedLeads.length,
    });
  } catch (err) {
    console.error("[seed] unexpected error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
